<?php
// Total items: 87
return [
    ["kode" => "1.01.01.0", "nama" => "DINAS PENDIDIKAN"],
    ["kode" => "1.01.01.01", "nama" => "UPTD UNIT LAYANAN DISABILITAS"],
    ["kode" => "1.02.01.0", "nama" => "DINAS KESEHATAN"],
    ["kode" => "1.02.01.01", "nama" => "PUSKESMAS LIANG ANGGANG"],
    ["kode" => "1.02.01.02", "nama" => "PUSKESMAS BANJARBARU UTARA"],
    ["kode" => "1.02.01.03", "nama" => "PUSKESMAS SUNGAI BESAR"],
    ["kode" => "1.02.01.04", "nama" => "PUSKESMAS SUNGAI ULIN"],
    ["kode" => "1.02.01.05", "nama" => "PUSKESMAS GUNTUNG PAYUNG"],
    ["kode" => "1.02.01.06", "nama" => "PUSKESMAS BANJARBARU SELATAN"],
    ["kode" => "1.02.01.07", "nama" => "PUSKESMAS LANDASAN ULIN TIMUR"],
    ["kode" => "1.02.01.08", "nama" => "PUSKESMAS LANDASAN ULIN"],
    ["kode" => "1.02.01.09", "nama" => "PUSKESMAS RAWAT INAP CEMPAKA"],
    ["kode" => "1.02.01.10", "nama" => "PUSKESMAS GUNTUNG MANGGIS"],
    ["kode" => "1.02.02.0", "nama" => "RUMAH SAKIT DAERAH IDAMAN"],
    ["kode" => "1.02.03.0", "nama" => "RSD IDAMAN KOTA BANJARBARU (BLUD)"],
    ["kode" => "1.03.01.0", "nama" => "DINAS PEKERJAAN UMUM DAN PENATAAN RUANG"],
    ["kode" => "1.04.01.0", "nama" => "DINAS PERUMAHAN DAN PERMUKIMAN"],
    ["kode" => "1.05.01.0", "nama" => "SATUAN POLISI PAMONG PRAJA"],
    ["kode" => "1.05.02.0", "nama" => "BADAN PENANGGULANGAN BENCANA DAERAH"],
    ["kode" => "1.05.03.0", "nama" => "BADAN KESATUAN BANGSA DAN POLITIK"],
    ["kode" => "1.06.01.0", "nama" => "DINAS SOSIAL"],
    ["kode" => "2.03.01.0", "nama" => "DINAS KETAHANAN PANGAN, PERTANIAN DAN PERIKANAN"],
    ["kode" => "2.03.01.01", "nama" => "UPT BALAI PEMBIBITAN TERNAK DAN PUSAT KESEHATAN HEWAN"],
    ["kode" => "2.03.01.02", "nama" => "UPT PRODUKSI PERIKANAN BUDIDAYA AIR TAWAR"],
    ["kode" => "2.05.01.0", "nama" => "DINAS LINGKUNGAN HIDUP"],
    ["kode" => "2.05.01.01", "nama" => "UPTD LABORATORIUM LINGKUNGAN HIDUP"],
    ["kode" => "2.06.01.0", "nama" => "DINAS KEPENDUDUKAN DAN PENCATATAN SIPIL"],
    ["kode" => "2.08.01.0", "nama" => "DINAS PEMBERDAYAAN PEREMPUAN, PERLINDUNGAN ANAK, PEMBERDAYAAN MASYARAKAT, PENGENDALIAN PENDUDUK DAN KB"],
    ["kode" => "2.09.01.0", "nama" => "DINAS PERHUBUNGAN"],
    ["kode" => "2.09.01.01", "nama" => "UPT PENGUJIAN DAN PERBENGKELAN KENDARAAN BERMOTOR"],
    ["kode" => "2.09.01.02", "nama" => "UPT PENGELOLAAN PERPARKIRAN"],
    ["kode" => "2.10.01.0", "nama" => "DINAS KOMUNIKASI DAN INFORMATIKA"],
    ["kode" => "2.11.01.0", "nama" => "DINAS KOPERASI, USAHA MIKRO DAN TENAGA KERJA"],
    ["kode" => "2.12.01.0", "nama" => "DINAS PENANAMAN MODAL DAN PELAYANAN TERPADU SATU PINTU"],
    ["kode" => "2.13.01.0", "nama" => "DINAS PEMUDA OLAHRAGA, KEBUDAYAAN DAN PARIWISATA"],
    ["kode" => "2.18.01.0", "nama" => "DINAS ARSIP DAN PERPUSTAKAAN DAERAH"],
    ["kode" => "3.06.01.0", "nama" => "DINAS PERDAGANGAN DAN PERINDUSTRIAN"],
    ["kode" => "3.06.01.01", "nama" => "UPT PENGELOLA PASAR BANJARBARU"],
    ["kode" => "3.06.01.02", "nama" => "UPT PENGELOLA PASAR ULIN RAYA"],
    ["kode" => "3.06.01.03", "nama" => "UPT PENGELOLA GUDANG TRANSITO"],
    ["kode" => "3.06.01.04", "nama" => "UPT METROLOGI"],
    ["kode" => "4.01.01.0", "nama" => "SEKRETARIAT DAERAH"],
    ["kode" => "4.01.01.01", "nama" => "SEKRETARIAT DAERAH-BAGIAN UMUM"],
    ["kode" => "4.01.01.02", "nama" => "SEKRETARIAT DAERAH-BAGIAN HUKUM"],
    ["kode" => "4.01.01.03", "nama" => "SEKRETARIAT DAERAH-BAGIAN PEMERINTAHAN"],
    ["kode" => "4.01.01.04", "nama" => "SEKRETARIAT DAERAH-BAGIAN ORGANISASI"],
    ["kode" => "4.01.01.05", "nama" => "SEKRETARIAT DAERAH-BAGIAN PROTOKOL DAN KOMUNIKASI PIMPINAN"],
    ["kode" => "4.01.01.06", "nama" => "SEKRETARIAT DAERAH-BAGIAN PEREKONOMIAN DAN SUMBER DAYA ALAM"],
    ["kode" => "4.01.01.07", "nama" => "SEKRETARIAT DAERAH-BAGIAN KESEJAHTERAAN RAKYAT"],
    ["kode" => "4.01.01.08", "nama" => "SEKRETARIAT DAERAH-BAGIAN PENGADAAN BARANG DAN JASA"],
    ["kode" => "4.01.01.09", "nama" => "SEKRETARIAT DAERAH-BAGIAN KERJASAMA DAN KEAGRARIAAN"],
    ["kode" => "4.01.01.10", "nama" => "KEPALA DAERAH DAN WAKIL KEPALA DAERAH"],
    ["kode" => "4.01.01.11", "nama" => "SEKRETARIAT DAERAH-BAGIAN ADMINISTRASI PEMBANGUNAN"],
    ["kode" => "4.02.01.0", "nama" => "INSPEKTORAT"],
    ["kode" => "4.03.01.0", "nama" => "BADAN PERENCANAAN PEMBANGUNAN, RISET DAN INOVASI DAERAH"],
    ["kode" => "4.04.01.0", "nama" => "BADAN PENGELOLAAN KEUANGAN DAN ASET DAERAH"],
    ["kode" => "4.04.02.0", "nama" => "BADAN PENGELOLAAN PAJAK DAN RETRIBUSI DAERAH"],
    ["kode" => "4.04.02.01", "nama" => "UPT PAJAK DAERAH WILAYAH I"],
    ["kode" => "4.04.02.02", "nama" => "UPT PAJAK DAERAH WILAYAH II"],
    ["kode" => "4.05.01.0", "nama" => "BADAN KEPEGAWAIAN DAN PENGEMBANGAN SUMBER DAYA MANUSIA"],
    ["kode" => "4.08.01.0", "nama" => "SEKRETARIAT DPRD"],
    ["kode" => "4.08.01.01", "nama" => "DEWAN PERWAKILAN RAKYAT DAERAH"],
    ["kode" => "4.11.01.0", "nama" => "KECAMATAN BANJARBARU SELATAN"],
    ["kode" => "4.11.01.01", "nama" => "KELURAHAN LOKTABAT SELATAN"],
    ["kode" => "4.11.01.02", "nama" => "KELURAHAN KEMUNING"],
    ["kode" => "4.11.01.03", "nama" => "KELURAHAN GUNTUNG PAIKAT"],
    ["kode" => "4.11.01.04", "nama" => "KELURAHAN SUNGAI BESAR"],
    ["kode" => "4.11.02.0", "nama" => "KECAMATAN BANJARBARU UTARA"],
    ["kode" => "4.11.02.01", "nama" => "KELURAHAN KOMET"],
    ["kode" => "4.11.02.02", "nama" => "KELURAHAN MENTAOS"],
    ["kode" => "4.11.02.03", "nama" => "KELURAHAN LOKTABAT UTARA"],
    ["kode" => "4.11.02.04", "nama" => "KELURAHAN SUNGAI ULIN"],
    ["kode" => "4.11.03.0", "nama" => "KECAMATAN CEMPAKA"],
    ["kode" => "4.11.03.01", "nama" => "KELURAHAN CEMPAKA"],
    ["kode" => "4.11.03.02", "nama" => "KELURAHAN PALAM"],
    ["kode" => "4.11.03.03", "nama" => "KELURAHAN BANGKAL"],
    ["kode" => "4.11.03.04", "nama" => "KELURAHAN SUNGAI TIUNG"],
    ["kode" => "4.11.04.0", "nama" => "KECAMATAN LANDASAN ULIN"],
    ["kode" => "4.11.04.01", "nama" => "KELURAHAN LANDASAN ULIN TIMUR"],
    ["kode" => "4.11.04.02", "nama" => "KELURAHAN GUNTUNG MANGGIS"],
    ["kode" => "4.11.04.03", "nama" => "KELURAHAN GUNTUNG PAYUNG"],
    ["kode" => "4.11.04.04", "nama" => "KELURAHAN SYAMSUDIN NOOR"],
    ["kode" => "4.11.05.0", "nama" => "KECAMATAN LIANG ANGGANG"],
    ["kode" => "4.11.05.01", "nama" => "KELURAHAN LANDASAN ULIN TENGAH"],
    ["kode" => "4.11.05.02", "nama" => "KELURAHAN LANDASAN ULIN UTARA"],
    ["kode" => "4.11.05.03", "nama" => "KELURAHAN LANDASAN ULIN BARAT"],
    ["kode" => "4.11.05.04", "nama" => "KELURAHAN LANDASAN ULIN SELATAN"],
];
